### ISSUE TITLE
Gentoo.org auto-sync seems to be broken?

### ISSUE THREAD

**Issue by lrvick** [funtoo/portage#1]
No updates in over a month to gentoo.org branch. Did some cron job die somewhere or has the repo moved?

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2116

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.
